/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasnicolahara;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrameKamar extends javax.swing.JFrame {

    /**
     * Creates new form FrameKamar
     */
    public FrameKamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nics_btn_grup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nics_txt_nama = new javax.swing.JTextField();
        nics_txt_alamat = new javax.swing.JTextField();
        nics_radio_tahunan = new javax.swing.JRadioButton();
        nics_radio_bulanan = new javax.swing.JRadioButton();
        nics_option = new javax.swing.JComboBox();
        nics_dispenser = new javax.swing.JCheckBox();
        nics_kipas_angin = new javax.swing.JCheckBox();
        nics_televisi = new javax.swing.JCheckBox();
        nics_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("APLIKASI PERHITUGAN BIAYA KAMAR");

        jLabel2.setText("Nama Penyewa :");

        jLabel3.setText("Alamat Asal :");

        jLabel4.setText("Periode :");

        jLabel5.setText("Cicilan :");

        jLabel6.setText("Fasilitas :");

        nics_btn_grup.add(nics_radio_tahunan);
        nics_radio_tahunan.setText("Tahunan");
        nics_radio_tahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nics_radio_tahunanActionPerformed(evt);
            }
        });

        nics_btn_grup.add(nics_radio_bulanan);
        nics_radio_bulanan.setText("Bulanan");
        nics_radio_bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nics_radio_bulananActionPerformed(evt);
            }
        });

        nics_dispenser.setText("Dispenser");

        nics_kipas_angin.setText("Kipas Angin");

        nics_televisi.setText("Televisi");

        nics_btn.setText("Hitung Biaya");
        nics_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nics_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nics_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nics_txt_nama)
                                .addComponent(nics_txt_alamat)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nics_radio_tahunan)
                                    .addGap(18, 18, 18)
                                    .addComponent(nics_radio_bulanan))
                                .addComponent(nics_option, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nics_dispenser)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nics_kipas_angin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nics_televisi))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nics_txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nics_txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nics_radio_tahunan)
                    .addComponent(nics_radio_bulanan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nics_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nics_dispenser)
                        .addComponent(nics_kipas_angin)
                        .addComponent(nics_televisi)))
                .addGap(18, 18, 18)
                .addComponent(nics_btn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nics_radio_tahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nics_radio_tahunanActionPerformed
        // TODO add your handling code here:
        nics_option.removeAllItems(); 
        nics_option.addItem("-Pilihan-"); 
        nics_option.addItem("3 Bulan"); 
        nics_option.addItem("6 Bulan"); 
        nics_option.addItem("1 Tahun");
    }//GEN-LAST:event_nics_radio_tahunanActionPerformed

    private void nics_radio_bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nics_radio_bulananActionPerformed
        // TODO add your handling code here:
        nics_option.removeAllItems(); 
        nics_option.addItem("-Pilihan-"); 
        nics_option.addItem("Mingguan"); 
        nics_option.addItem("Bulanan");
    }//GEN-LAST:event_nics_radio_bulananActionPerformed

    private void nics_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nics_btnActionPerformed
        // TODO add your handling code here:
        double total = 0, fasilitas = 0;
        int jumCicilan = 0;
        boolean salah = false;
        if (nics_radio_tahunan.isSelected()) {
        total = 6500000;
        //pilihan cicilan
        if (nics_option.getSelectedIndex() == 1) {
        jumCicilan = 4;

        } else if (nics_option.getSelectedIndex() == 2) { jumCicilan = 2;

        } else if (nics_option.getSelectedIndex() == 3) { jumCicilan = 1;

        } else {
        salah = true;
        }

        //pilihan fasilitas
        if (nics_dispenser.isSelected()) {
        fasilitas = fasilitas + 240000;
        }
        if (nics_televisi.isSelected()) {
        fasilitas = fasilitas + 272000;
        }

        if (nics_kipas_angin.isSelected()) {
        fasilitas = fasilitas + 15000;
        }

        } else if (nics_radio_bulanan.isSelected()) { total = 800000;

        //pilihan cicilan

        if (nics_option.getSelectedIndex() == 1) { jumCicilan = 3;

        } else if (nics_option.getSelectedIndex() == 2) { jumCicilan = 1;

        } else {
        salah = true;
        }

        //pilihan fasilitas
        if (nics_dispenser.isSelected()) {
        fasilitas = fasilitas + 30000;
        }
        if (nics_televisi.isSelected()) {
        fasilitas = fasilitas + 272000;
        }

        if (nics_kipas_angin.isSelected()) {
        fasilitas = fasilitas + 5000;
        }

        } else {
        salah = true;
        }

        //hitung total biaya per-1x bayar ditambah fasilitas
        total = total + fasilitas;
        total = total / jumCicilan;

        if (nics_txt_nama.getText().isEmpty() || nics_txt_alamat.getText().isEmpty()) { 
            salah = true;
        }
        
        if (salah) {
            JOptionPane.showMessageDialog(this, "Periksa Nama & Alamat,\n"+ "Pilihan Bulanan/Tahunan,\n" + "dan Jumlah Cicilan", "Status", JOptionPane.WARNING_MESSAGE);
        } else {
            //format tampilan uang
            DecimalFormat df = (DecimalFormat) DecimalFormat.getCurrencyInstance();
            DecimalFormatSymbols dfs = new DecimalFormatSymbols();
            dfs.setCurrencySymbol("");
            dfs.setMonetaryDecimalSeparator(',');
            dfs.setGroupingSeparator('.');

            df.setDecimalFormatSymbols(dfs);

            //format tampilan dialog
            String pesan = "";
            pesan = "Penyewa: " + nics_txt_nama.getText();

            pesan += "\nAlamat Asal: " + nics_txt_alamat.getText() + "\n\n";
            pesan += "Total Bayar 1x: " + df.format(total);

            pesan += "\nJumlah Cicilan: " + jumCicilan;

            pesan += "\nTotal Pengeluaran: " + df.format(total * jumCicilan); JOptionPane.showMessageDialog(this, pesan, "Jumlah Biaya",

            JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_nics_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton nics_btn;
    private javax.swing.ButtonGroup nics_btn_grup;
    private javax.swing.JCheckBox nics_dispenser;
    private javax.swing.JCheckBox nics_kipas_angin;
    private javax.swing.JComboBox nics_option;
    private javax.swing.JRadioButton nics_radio_bulanan;
    private javax.swing.JRadioButton nics_radio_tahunan;
    private javax.swing.JCheckBox nics_televisi;
    private javax.swing.JTextField nics_txt_alamat;
    private javax.swing.JTextField nics_txt_nama;
    // End of variables declaration//GEN-END:variables
}
